Let's catch Throwable so that we correctly shut ourselves down if something unexceptional causes startup failure, like NoClassDefFoundError.
git-svn-id: svn+ssh://src.earth.threerings.net/narya/trunk@6335 542714f4-19e9-0310-aa3c-eee0fc999fb1